import type { Metadata } from "next";
import React from "react";
import {
  Geist as geistFont,
  Geist_Mono as geistMonoFont,
} from "next/font/google";
import "./globals.css";

const geistSans = geistFont({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = geistMonoFont({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang={"en"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

